import fs from 'fs';
import path from 'path';

const OUTPUT_DIR = 'client/public';
const DATA_DIR = 'client/public/data';
const BASE_URL = 'https://reel-interview.github.io';

// Load stats from static data (generated by fetch-questions-for-build.js)
function loadStats() {
  try {
    const statsPath = path.join(DATA_DIR, 'stats.json');
    return JSON.parse(fs.readFileSync(statsPath, 'utf-8'));
  } catch {
    return { totalQuestions: 0, totalChannels: 0, channels: [], lastUpdated: new Date().toISOString() };
  }
}

// Escape XML special characters
function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Generate RSS XML
function generateRssFeed() {
  const stats = loadStats();
  
  // Create a simple RSS feed based on available channels
  const channelItems = stats.channels.map((channel) => {
    return `
    <item>
      <title>${escapeXml(channel.id)} - ${channel.total} Questions</title>
      <description><![CDATA[Practice ${channel.total} interview questions in ${channel.id}. Difficulty breakdown: ${channel.beginner} beginner, ${channel.intermediate} intermediate, ${channel.advanced} advanced.]]></description>
      <pubDate>${new Date(stats.lastUpdated).toUTCString()}</pubDate>
      <guid isPermaLink="false">${channel.id}-${stats.lastUpdated}</guid>
      <link>${BASE_URL}/channel/${channel.id}</link>
      <category>${escapeXml(channel.id)}</category>
    </item>`;
  }).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Code Reels - Interview Questions</title>
    <description>Master technical interviews with ${stats.totalQuestions} questions across ${stats.totalChannels} channels. System design, algorithms, frontend, backend, DevOps, and more.</description>
    <link>${BASE_URL}</link>
    <atom:link href="${BASE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <ttl>60</ttl>
    <image>
      <url>${BASE_URL}/favicon.svg</url>
      <title>Code Reels</title>
      <link>${BASE_URL}</link>
    </image>
    ${channelItems}
  </channel>
</rss>`;
}

// Main
function main() {
  console.log('=== Generating RSS Feed ===\n');

  // Check if data files exist
  if (!fs.existsSync(path.join(DATA_DIR, 'stats.json'))) {
    console.log('⚠️ No stats.json found. Run fetch-questions-for-build.js first.');
    console.log('   Creating minimal RSS feed...');
  }

  const rssFeed = generateRssFeed();

  // Ensure output directory exists
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  // Write RSS file
  const outputPath = path.join(OUTPUT_DIR, 'rss.xml');
  fs.writeFileSync(outputPath, rssFeed);

  console.log(`✅ RSS feed generated: ${outputPath}`);
  console.log(`   Base URL: ${BASE_URL}`);
}

main();
