-- Create learning paths table for dynamically generated career paths
CREATE TABLE IF NOT EXISTS learningPaths (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  pathType TEXT NOT NULL, -- 'company', 'job-title', 'skill', 'certification'
  targetCompany TEXT, -- e.g., 'Google', 'Amazon', 'Meta'
  targetJobTitle TEXT, -- e.g., 'frontend-engineer', 'backend-engineer'
  difficulty TEXT NOT NULL, -- 'beginner', 'intermediate', 'advanced'
  estimatedHours INTEGER DEFAULT 40,
  questionIds TEXT NOT NULL, -- JSON array of question IDs in recommended order
  channels TEXT NOT NULL, -- JSON array of channels covered
  tags TEXT, -- JSON array of tags
  prerequisites TEXT, -- JSON array of prerequisite path IDs
  learningObjectives TEXT, -- JSON array of learning objectives
  milestones TEXT, -- JSON array of milestone objects
  popularity INTEGER DEFAULT 0, -- How many users have started this path
  completionRate INTEGER DEFAULT 0, -- Percentage of users who completed
  averageRating INTEGER DEFAULT 0, -- 0-100 user rating
  metadata TEXT, -- JSON for additional data (RAG insights, company patterns, etc.)
  status TEXT DEFAULT 'active', -- 'active', 'draft', 'archived'
  createdAt TEXT NOT NULL,
  lastUpdated TEXT,
  lastGenerated TEXT -- When this path was last regenerated by the daily job
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_learningPaths_pathType ON learningPaths(pathType);
CREATE INDEX IF NOT EXISTS idx_learningPaths_targetCompany ON learningPaths(targetCompany);
CREATE INDEX IF NOT EXISTS idx_learningPaths_targetJobTitle ON learningPaths(targetJobTitle);
CREATE INDEX IF NOT EXISTS idx_learningPaths_difficulty ON learningPaths(difficulty);
CREATE INDEX IF NOT EXISTS idx_learningPaths_status ON learningPaths(status);
CREATE INDEX IF NOT EXISTS idx_learningPaths_popularity ON learningPaths(popularity DESC);
